### PR TITLE
Fix tests with libxml2 2.9.12

### LINKED ISSUE #172: Tests failing with libxml2 2.9.12
```
Finished in 1.912630s, 182.4712 runs/s, 22097.8406 assertions/s.

  1) Failure:
TestParserContext#test_parse_error [/<<PKGBUILDDIR>>/test/test_parser_context.rb:188]:
Expected: 17
  Actual: 0

  2) Failure:
TestSaxParser#test_parse_error [/<<PKGBUILDDIR>>/test/test_sax_parser.rb:257]:
--- expected
+++ actual
@@ -1 +1 @@
-"error: Fatal error: EndTag: '</' not found at :2."
+"error: Fatal error: Premature end of data in tag Results line 1 at :2."


  3) Failure:
TestParser#test_error [/<<PKGBUILDDIR>>/test/test_parser.rb:274]:
Expected: 20
  Actual: 18

349 runs, 42265 assertions, 3 failures, 0 errors, 0 skips
DOCUMENT
version=1.0
encoding=utf-8
URL=/<<BUILDDIR>>/ruby-libxml-3....
standalone=true
  ELEMENT bands
    ATTRIBUTE genre
      TEXT
        content=metal
    ELEMENT m#C3#B6tley_cr#C3#BCe
      ATTRIBUTE country
        TEXT interned
          content=us
      TEXT
        content=M#C3#B6tley Cr#C3#BCe is an American heavy metal...
    ELEMENT iron_maiden
      ATTRIBUTE country
        TEXT interned
          content=uk
      TEXT
        content=Iron Maiden is a British heavy metal ban...
    ELEMENT bands
      ATTRIBUTE genre
        TEXT
          content=metal
      ELEMENT m#C3#B6tley_cr#C3#BCe
        ATTRIBUTE country
          TEXT
            content=us
        TEXT
          content=M#C3#B6tley Cr#C3#BCe is an American heavy metal...
      ELEMENT iron_maiden
        ATTRIBUTE country
          TEXT
            content=uk
        TEXT
          content=Iron Maiden is a British heavy metal ban...
rake aborted!
```

### PR DESCRIPTION
**Pull request by sergiodj**
This patch fixes a number of test issues that started happening after
Ubuntu moved to libmlx2 2.9.12+dfsg-2.  They are:

* num_chars has been deprecated and is now always set to 0.  See
  https://gitlab.gnome.org/GNOME/libxml2/-/commit/438e595a8cccbe48de3a0be2e0c291cfe97080b1.

* The "Fatal error: EndTag..." message has been reverted back to
  "Fatal error: Premature end of data...".

* Some adjustments to the expected values of error.int1, error.int2
  and error.str1.

Closes #172

### CODE REVIEW

**Comment by cfis** [comment]
Thanks!

File: test/test_sax_parser.rb [hunk 1]
```diff
@@ -254,21 +254,21 @@ def test_parse_error
...
-    assert_equal("Fatal error: EndTag: '</' not found at :2.", error.message)
+    assert_equal("Fatal error: Premature end of data in tag Results line 1 at :2.", error.message)
     assert_equal(LibXML::XML::Error::PARSER, error.domain)
-    assert_equal(LibXML::XML::Error::LTSLASH_REQUIRED, error.code)
+    assert_equal(LibXML::XML::Error::TAG_NOT_FINISHED, error.code)
     assert_equal(LibXML::XML::Error::FATAL, error.level)
     assert_nil(error.file)
     assert_equal(2, error.line)
-    assert_nil(error.str1)
+    refuse_nil(error.str1)
```
Comment (mapreri) [inline test/test_sax_parser.rb:268]: I think this should have been `refute_nil` instead?

Comment (sergiodj) [reply test/test_sax_parser.rb:268]: Yes.  I've opened https://github.com/xml4r/libxml-ruby/pull/175 to fix this.  Thanks.
